"""empty message

Revision ID: 851f284559e2
Revises: 85a40b099e0d
Create Date: 2025-08-08 00:33:31.108521

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "851f284559e2"
down_revision: Union[str, None] = "85a40b099e0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "branch", "username", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=255), existing_nullable=False
    )
    op.alter_column(
        "branch", "phone", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=255), existing_nullable=False
    )
    op.alter_column(
        "company", "username", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=255), existing_nullable=False
    )
    op.alter_column(
        "company", "phone", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=20), existing_nullable=False
    )
    op.alter_column(
        "menu", "username", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=255), existing_nullable=False
    )
    op.alter_column(
        "menu_item",
        "username",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "order", "username", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=255), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order", "username", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=15), existing_nullable=False
    )
    op.alter_column(
        "menu_item",
        "username",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "menu", "username", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=15), existing_nullable=False
    )
    op.alter_column(
        "company", "phone", existing_type=sa.String(length=20), type_=sa.VARCHAR(length=15), existing_nullable=False
    )
    op.alter_column(
        "company", "username", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=15), existing_nullable=False
    )
    op.alter_column(
        "branch", "phone", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=15), existing_nullable=False
    )
    op.alter_column(
        "branch", "username", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=15), existing_nullable=False
    )
    # ### end Alembic commands ###
