"""empty message

Revision ID: 53be3f1f33a5
Revises: 1094cc68de30
Create Date: 2025-08-03 17:30:41.630983

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53be3f1f33a5"
down_revision: Union[str, None] = "1094cc68de30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_order_status"), "order", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_status"), table_name="order")
    # ### end Alembic commands ###
