"""empty message

Revision ID: a1a4e624cd2c
Revises: 5411c6af2131
Create Date: 2025-08-02 13:36:32.693930

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1a4e624cd2c"
down_revision: Union[str, None] = "5411c6af2131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "menu_item",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.add_column("order", sa.Column("branch_id", sa.Integer(), nullable=False))
    op.alter_column(
        "order",
        "total_amount",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_constraint("order_menu_item_id_fkey", "order", type_="foreignkey")
    op.create_foreign_key(None, "order", "branch", ["branch_id"], ["id"])
    op.drop_column("order", "price")
    op.drop_column("order", "menu_item_id")
    op.drop_column("order", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("order", sa.Column("menu_item_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("order", sa.Column("price", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, "order", type_="foreignkey")
    op.create_foreign_key("order_menu_item_id_fkey", "order", "menu_item", ["menu_item_id"], ["id"])
    op.alter_column(
        "order",
        "total_amount",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.drop_column("order", "branch_id")
    op.alter_column(
        "menu_item",
        "price",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
