"""empty message

Revision ID: eafb11e8dd78
Revises: 7777f6a59269
Create Date: 2025-08-02 15:02:23.141930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafb11e8dd78'
down_revision: Union[str, None] = '7777f6a59269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity <= 99', name='ck_quantity_reasonable'),
    sa.CheckConstraint('quantity > 0', name='ck_quantity_positive'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'menu_item_id', name='uq_user_menu_item')
    )
    op.create_index(op.f('ix_basket_menu_item_id'), 'basket', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_basket_user_id'), 'basket', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basket_user_id'), table_name='basket')
    op.drop_index(op.f('ix_basket_menu_item_id'), table_name='basket')
    op.drop_table('basket')
    # ### end Alembic commands ###
