"""empty message

Revision ID: 845b3c357cc1
Revises: c0d810873a5c
Create Date: 2025-07-21 18:10:37.649444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845b3c357cc1'
down_revision: Union[str, None] = 'c0d810873a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('menu_items', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('menu_items', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.alter_column('menu_items', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('menu_items_name_key', 'menu_items', type_='unique')
    op.alter_column('menus', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menus', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('menu_items_name_key', 'menu_items', ['name'])
    op.alter_column('menu_items', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('menu_items', 'is_available')
    op.drop_column('menu_items', 'price')
    op.drop_column('menu_items', 'description')
    # ### end Alembic commands ###
