"""empty message

Revision ID: eb0127b93865
Revises: be2dcb497b32
Create Date: 2025-07-12 18:51:44.543663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb0127b93865'
down_revision: Union[str, None] = 'be2dcb497b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('admin', 'company', 'cafeteria', 'user', name='user_role'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
