"""empty message

Revision ID: 65922829c116
Revises: cbe712ec03c4
Create Date: 2025-07-16 11:30:02.277117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65922829c116'
down_revision: Union[str, None] = 'cbe712ec03c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'company', 'branche', 'user', name='user_role'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'company', 'branche', 'user', name='user_role'),
               nullable=False)
    # ### end Alembic commands ###
