"""empty message

Revision ID: da1e985a6ea6
Revises: 4f1c23c7b662
Create Date: 2025-07-27 16:56:12.940680

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da1e985a6ea6"
down_revision: Union[str, None] = "4f1c23c7b662"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "menu_item",
        "price",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "menu_item", "is_available", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("menu_item", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_item",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "menu_item", "is_available", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "menu_item",
        "price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
