"""empty message

Revision ID: a13cad1ac652
Revises: 780108106c8d
Create Date: 2025-08-07 11:57:11.654009

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a13cad1ac652"
down_revision: Union[str, None] = "780108106c8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_codes_code"), "verification_codes", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_verification_codes_email"),
        "verification_codes",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_codes_expires_at"),
        "verification_codes",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_codes_phone"),
        "verification_codes",
        ["phone"],
        unique=False,
    )
    op.drop_index("ix_payment_order_id", table_name="payment")
    op.drop_index("ix_payment_status", table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "stripe_payment_intent_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                "REFUNDED",
                name="payment_status",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            postgresql.ENUM("CARD", "WALLET", "BANK_TRANSFER", name="payment_method"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stripe_client_secret",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("failure_reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "receipt_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name="payment_order_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="payment_pkey"),
        sa.UniqueConstraint(
            "stripe_payment_intent_id", name="payment_stripe_payment_intent_id_key"
        ),
    )
    op.create_index("ix_payment_status", "payment", ["status"], unique=False)
    op.create_index("ix_payment_order_id", "payment", ["order_id"], unique=False)
    op.drop_index(op.f("ix_verification_codes_phone"), table_name="verification_codes")
    op.drop_index(
        op.f("ix_verification_codes_expires_at"), table_name="verification_codes"
    )
    op.drop_index(op.f("ix_verification_codes_email"), table_name="verification_codes")
    op.drop_index(op.f("ix_verification_codes_code"), table_name="verification_codes")
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
