"""empty message

Revision ID: 780108106c8d
Revises: 50c235054b68
Create Date: 2025-08-06 16:49:44.472487

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "780108106c8d"
down_revision: Union[str, None] = "50c235054b68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                "REFUNDED",
                name="payment_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("CARD", "WALLET", "BANK_TRANSFER", name="payment_method"),
            nullable=True,
        ),
        sa.Column("stripe_client_secret", sa.String(length=255), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("receipt_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_payment_intent_id"),
    )
    op.create_index(op.f("ix_payment_order_id"), "payment", ["order_id"], unique=False)
    op.create_index(op.f("ix_payment_status"), "payment", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_status"), table_name="payment")
    op.drop_index(op.f("ix_payment_order_id"), table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###
