"""empty message

Revision ID: 3944060fb8b9
Revises: 6facad4d7a2a
Create Date: 2025-07-21 13:59:52.076806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3944060fb8b9'
down_revision: Union[str, None] = '6facad4d7a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('company_user_id_fkey', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'users', ['owner_id'], ['id'])
    op.drop_column('company', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key('company_user_id_fkey', 'company', 'users', ['user_id'], ['id'])
    op.drop_column('company', 'owner_id')
    # ### end Alembic commands ###
