"""empty message

Revision ID: c334c31c49d5
Revises: 04074fd9027d
Create Date: 2025-07-27 17:19:54.789396

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c334c31c49d5"
down_revision: Union[str, None] = "04074fd9027d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone", existing_type=sa.VARCHAR(length=15), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "phone", existing_type=sa.VARCHAR(length=15), nullable=False
    )
    # ### end Alembic commands ###
