"""empty message

Revision ID: 85a40b099e0d
Revises: e603d0d0b4b2
Create Date: 2025-08-08 00:31:49.486337

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85a40b099e0d"
down_revision: Union[str, None] = "e603d0d0b4b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_code",
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verification_code_code"), "verification_code", ["code"], unique=False)
    op.create_index(op.f("ix_verification_code_email"), "verification_code", ["email"], unique=False)
    op.create_index(op.f("ix_verification_code_phone"), "verification_code", ["phone"], unique=False)
    op.drop_index("ix_verification_codes_code", table_name="verification_codes")
    op.drop_index("ix_verification_codes_email", table_name="verification_codes")
    op.drop_index("ix_verification_codes_phone", table_name="verification_codes")
    op.drop_table("verification_codes")
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=255), existing_nullable=False
    )
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "user", "phone", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=255), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "phone", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=15), existing_nullable=True
    )
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "user", "username", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=15), existing_nullable=False
    )
    op.create_table(
        "verification_codes",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("code", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="verification_codes_pkey"),
    )
    op.create_index("ix_verification_codes_phone", "verification_codes", ["phone"], unique=False)
    op.create_index("ix_verification_codes_email", "verification_codes", ["email"], unique=False)
    op.create_index("ix_verification_codes_code", "verification_codes", ["code"], unique=False)
    op.drop_index(op.f("ix_verification_code_phone"), table_name="verification_code")
    op.drop_index(op.f("ix_verification_code_email"), table_name="verification_code")
    op.drop_index(op.f("ix_verification_code_code"), table_name="verification_code")
    op.drop_table("verification_code")
    # ### end Alembic commands ###
