"""empty message

Revision ID: 6facad4d7a2a
Revises: 37cf839fded1
Create Date: 2025-07-21 13:56:52.079829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6facad4d7a2a'
down_revision: Union[str, None] = '37cf839fded1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('branches_user_id_fkey', 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'users', ['owner_id'], ['id'])
    op.drop_column('branches', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key('branches_user_id_fkey', 'branches', 'users', ['user_id'], ['id'])
    op.drop_column('branches', 'owner_id')
    # ### end Alembic commands ###
